#!/bin/bash

# Get the Resources directory inside the app bundle
RESOURCES_DIR="$(cd "$(dirname "$0")/../Resources" && pwd)"

# Change to the Resources directory
cd "$RESOURCES_DIR"

# Open Terminal and run the script
osascript -e "tell application \"Terminal\"
    do script \"cd '$RESOURCES_DIR' && ./run.sh\"
    activate
end tell"
